export const Routes = {
    YourStory: '/yourstory',
    YourStoryPosted: '/yourstoryposted',
    Admin: '/admin',
    Post: '/post',
    Messages: '/messages',
    Contacted: '/contacted',
    Unassigned: '/unassigned',
    InProgress: '/inprogress',
    Finished: '/finished',
    Featured: '/featured',
    Inquiries: '/inquiries',
    Privacy: '/privacy',
    TermsAndConditions: '/termsandconditions',
};
